### ISSUE TITLE
debezium-cdc-without-kafka fails on 4.4

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet-demos#136]
Works on 4.3, on 4.4 gives

```
hazelcast-jet_1         | Caused by: java.lang.ClassNotFoundException: com.hazelcast.jet.contrib.debezium.HazelcastListDatabaseHistory
hazelcast-jet_1         | 	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
hazelcast-jet_1         | 	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
hazelcast-jet_1         | 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
hazelcast-jet_1         | 	at io.debezium.config.Instantiator.getInstanceWithProvidedConstructorType(Instantiator.java:50) ~[hazelcast-jet-cdc-debezium-4.4.jar:?]
hazelcast-jet_1         | 	at io.debezium.config.Instantiator.getInstance(Instantiator.java:28) ~[hazelcast-jet-cdc-debezium-4.4.jar:?]
hazelcast-jet_1         | 	at io.debezium.config.Configuration.getInstance(Configuration.java:1463) ~[hazelcast-jet-cdc-debezium-4.4.jar:?]
hazelcast-jet_1         | 	at io.debezium.config.Configuration.getInstance(Configuration.java:1449) ~[hazelcast-jet-cdc-debezium-4.4.jar:?]
hazelcast-jet_1         | 	at io.debezium.connector.mysql.MySqlSchema.<init>(MySqlSchema.java:126) ~[hazelcast-jet-cdc-mysql-4.4.jar:?]
hazelcast-jet_1         | 	at io.debezium.connector.mysql.MySqlTaskContext.<init>(MySqlTaskContext.java:86) ~[hazelcast-jet-cdc-mysql-4.4.jar:?]
hazelcast-jet_1         | 	at io.debezium.connector.mysql.MySqlTaskContext.<init>(MySqlTaskContext.java:52) ~[hazelcast-jet-cdc-mysql-4.4.jar:?]
hazelcast-jet_1         | 	at io.debezium.connector.mysql.MySqlConnectorTask.createAndStartTaskContext(MySqlConnectorTask.java:357) ~[hazelcast-jet-cdc-mysql-4.4.jar:?]
hazelcast-jet_1         | 	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:143) ~[hazelcast-jet-cdc-mysql-4.4.jar:?]
hazelcast-jet_1         | 	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:101) ~[hazelcast-jet-cdc-debezium-4.4.jar:?]
hazelcast-jet_1         | 	at com.hazelcast.jet.contrib.connect.KafkaConnectSources$Context.fillBuffer(KafkaConnectSources.java:133) ~[?:?]
hazelcast-jet_1         | 	at com.hazelcast.function.BiConsumerEx.accept(BiConsumerEx.java:47) ~[hazelcast-jet-4.4.jar:4.4]
hazelcast-jet_1         | 	at com.hazelcast.jet.impl.connector.ConvenientSourceP.complete(ConvenientSourceP.java:117) ~[hazelcast-jet-4.4.jar:4.4]
hazelcast-jet_1         | 	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:472) ~[hazelcast-jet-4.4.jar:4.4]
hazelcast-jet_1         | 	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:372) ~[hazelcast-jet-4.4.jar:4.4]
hazelcast-jet_1         | 	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:247) ~[hazelcast-jet-4.4.jar:4.4]
hazelcast-jet_1         | 	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:293) ~[hazelcast-jet-4.4.jar:4.4]
hazelcast-jet_1         | 	... 5 more
```

**Comment by neilstevenson** [comment]
Doesn't work on 4.3, on 4.2 gives:

```
hazelcast-jet_1         | Caused by: java.lang.AbstractMethodError: Receiver class com.hazelcast.jet.contrib.debezium.HazelcastListDatabaseHistory does not define or inherit an implementation of the resolved method 'abstract boolean storageExists()' of interface io.debezium.relational.history.DatabaseHistory.
hazelcast-jet_1         | 	at io.debezium.connector.mysql.MySqlSchema.intializeHistoryStorage(MySqlSchema.java:284) ~[?:?]
hazelcast-jet_1         | 	at io.debezium.connector.mysql.MySqlTaskContext.initializeHistoryStorage(MySqlTaskContext.java:195) ~[?:?]
hazelcast-jet_1         | 	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:144) ~[?:?]
hazelcast-jet_1         | 	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:106) ~[?:?]
hazelcast-jet_1         | 	at com.hazelcast.jet.contrib.connect.KafkaConnectSources$Context.fillBuffer(KafkaConnectSources.java:133) ~[?:?]
hazelcast-jet_1         | 	at com.hazelcast.function.BiConsumerEx.accept(BiConsumerEx.java:47) ~[hazelcast-jet-4.2.jar:4.2]
hazelcast-jet_1         | 	at com.hazelcast.jet.impl.connector.ConvenientSourceP.complete(ConvenientSourceP.java:117) ~[hazelcast-jet-4.2.jar:4.2]
hazelcast-jet_1         | 	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:465) ~[hazelcast-jet-4.2.jar:4.2]
hazelcast-jet_1         | 	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:365) ~[hazelcast-jet-4.2.jar:4.2]
hazelcast-jet_1         | 	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:240) ~[hazelcast-jet-4.2.jar:4.2]
hazelcast-jet_1         | 	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:293) ~[hazelcast-jet-4.2.jar:4.2]
hazelcast-jet_1         | 	... 5 more

```

**Comment by neilstevenson** [comment]
See https://github.com/hazelcast/hazelcast-jet-demos/issues/121
