### ISSUE TITLE
tensorflow example fails on 4.4

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet-demos#137]
Using 
```
mvn compile exec:java -Dexec.mainClass=InProcessClassification -Dexec.args="data"
```
as per README.md https://github.com/hazelcast/hazelcast-jet-demos/blob/master/tensorflow/README.md gives
```
com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.InvalidObjectException: ReflectiveOperationException during deserialization
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:103)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:211)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:66)
	at com.hazelcast.jet.impl.JobCoordinationService.deserializeJobDefinition(JobCoordinationService.java:876)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:208)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1039)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1060)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.io.InvalidObjectException: ReflectiveOperationException during deserialization
	at java.base/java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:244)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1316)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2244)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1712)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2540)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2434)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2235)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1712)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:519)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:477)
	at java.base/java.util.ArrayList.readObject(ArrayList.java:899)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1226)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2401)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2235)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1712)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:519)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:477)
	at java.base/java.util.HashMap.readObject(HashMap.java:1551)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1226)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2401)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2235)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1712)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2540)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2434)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2235)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1712)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:519)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:477)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:83)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:76)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:205)
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:242)
	... 55 more
Caused by: java.lang.IllegalArgumentException: Invalid lambda deserialization
	at InProcessClassification.$deserializeLambda$(InProcessClassification.java:1)
	... 60 more
[WARNING] 
com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.InvalidObjectException: ReflectiveOperationException during deserialization
    at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException (SerializationUtil.java:103)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject (AbstractSerializationService.java:211)
    at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader (CustomClassLoadedObject.java:66)
    at com.hazelcast.jet.impl.JobCoordinationService.deserializeJobDefinition (JobCoordinationService.java:876)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1 (JobCoordinationService.java:208)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46 (JobCoordinationService.java:1039)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47 (JobCoordinationService.java:1060)
    at com.hazelcast.internal.util.executor.CompletableFutureTask.run (CompletableFutureTask.java:64)
    at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run (CachedExecutorServiceDelegate.java:217)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:630)
    at java.lang.Thread.run (Thread.java:832)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun (HazelcastManagedThread.java:76)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.run (HazelcastManagedThread.java:102)
Caused by: java.io.InvalidObjectException: ReflectiveOperationException during deserialization
    at java.lang.invoke.SerializedLambda.readResolve (SerializedLambda.java:244)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at java.io.ObjectStreamClass.invokeReadResolve (ObjectStreamClass.java:1316)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2244)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.defaultReadFields (ObjectInputStream.java:2540)
    at java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:2434)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2235)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:519)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:477)
    at java.util.ArrayList.readObject (ArrayList.java:899)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at java.io.ObjectStreamClass.invokeReadObject (ObjectStreamClass.java:1226)
    at java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:2401)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2235)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:519)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:477)
    at java.util.HashMap.readObject (HashMap.java:1551)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at java.io.ObjectStreamClass.invokeReadObject (ObjectStreamClass.java:1226)
    at java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:2401)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2235)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.defaultReadFields (ObjectInputStream.java:2540)
    at java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:2434)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2235)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:519)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:477)
    at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read (JavaDefaultSerializers.java:83)
    at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read (JavaDefaultSerializers.java:76)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read (StreamSerializerAdapter.java:44)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject (AbstractSerializationService.java:205)
    at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader (CustomClassLoadedObject.java:66)
    at com.hazelcast.jet.impl.JobCoordinationService.deserializeJobDefinition (JobCoordinationService.java:876)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1 (JobCoordinationService.java:208)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46 (JobCoordinationService.java:1039)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47 (JobCoordinationService.java:1060)
    at com.hazelcast.internal.util.executor.CompletableFutureTask.run (CompletableFutureTask.java:64)
    at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run (CachedExecutorServiceDelegate.java:217)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:630)
    at java.lang.Thread.run (Thread.java:832)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun (HazelcastManagedThread.java:76)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.run (HazelcastManagedThread.java:102)
Caused by: java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at java.lang.invoke.SerializedLambda.readResolve (SerializedLambda.java:242)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at java.io.ObjectStreamClass.invokeReadResolve (ObjectStreamClass.java:1316)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2244)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.defaultReadFields (ObjectInputStream.java:2540)
    at java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:2434)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2235)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:519)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:477)
    at java.util.ArrayList.readObject (ArrayList.java:899)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at java.io.ObjectStreamClass.invokeReadObject (ObjectStreamClass.java:1226)
    at java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:2401)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2235)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:519)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:477)
    at java.util.HashMap.readObject (HashMap.java:1551)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at java.io.ObjectStreamClass.invokeReadObject (ObjectStreamClass.java:1226)
    at java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:2401)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2235)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.defaultReadFields (ObjectInputStream.java:2540)
    at java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:2434)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2235)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:519)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:477)
    at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read (JavaDefaultSerializers.java:83)
    at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read (JavaDefaultSerializers.java:76)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read (StreamSerializerAdapter.java:44)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject (AbstractSerializationService.java:205)
    at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader (CustomClassLoadedObject.java:66)
    at com.hazelcast.jet.impl.JobCoordinationService.deserializeJobDefinition (JobCoordinationService.java:876)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1 (JobCoordinationService.java:208)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46 (JobCoordinationService.java:1039)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47 (JobCoordinationService.java:1060)
    at com.hazelcast.internal.util.executor.CompletableFutureTask.run (CompletableFutureTask.java:64)
    at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run (CachedExecutorServiceDelegate.java:217)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:630)
    at java.lang.Thread.run (Thread.java:832)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun (HazelcastManagedThread.java:76)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.run (HazelcastManagedThread.java:102)
Caused by: java.lang.IllegalArgumentException: Invalid lambda deserialization
    at InProcessClassification.$deserializeLambda$ (InProcessClassification.java:1)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at java.lang.invoke.SerializedLambda.readResolve (SerializedLambda.java:242)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at java.io.ObjectStreamClass.invokeReadResolve (ObjectStreamClass.java:1316)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2244)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.defaultReadFields (ObjectInputStream.java:2540)
    at java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:2434)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2235)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:519)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:477)
    at java.util.ArrayList.readObject (ArrayList.java:899)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at java.io.ObjectStreamClass.invokeReadObject (ObjectStreamClass.java:1226)
    at java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:2401)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2235)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:519)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:477)
    at java.util.HashMap.readObject (HashMap.java:1551)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at java.io.ObjectStreamClass.invokeReadObject (ObjectStreamClass.java:1226)
    at java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:2401)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2235)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.defaultReadFields (ObjectInputStream.java:2540)
    at java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:2434)
    at java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:2235)
    at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1712)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:519)
    at java.io.ObjectInputStream.readObject (ObjectInputStream.java:477)
    at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read (JavaDefaultSerializers.java:83)
    at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read (JavaDefaultSerializers.java:76)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read (StreamSerializerAdapter.java:44)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject (AbstractSerializationService.java:205)
    at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader (CustomClassLoadedObject.java:66)
    at com.hazelcast.jet.impl.JobCoordinationService.deserializeJobDefinition (JobCoordinationService.java:876)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1 (JobCoordinationService.java:208)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46 (JobCoordinationService.java:1039)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47 (JobCoordinationService.java:1060)
    at com.hazelcast.internal.util.executor.CompletableFutureTask.run (CompletableFutureTask.java:64)
    at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run (CachedExecutorServiceDelegate.java:217)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:630)
    at java.lang.Thread.run (Thread.java:832)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun (HazelcastManagedThread.java:76)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.run (HazelcastManagedThread.java:102)
```

**Comment by neilstevenson** [comment]
See https://github.com/hazelcast/hazelcast-jet-demos/issues/121
