### ISSUE TITLE
image recognition fails to run

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-jet-demos#22]
```mvn exec:java```

```
[hz._hzInstance_1_jet.async.thread-3] WARN com.hazelcast.jet.impl.MasterContext - [172.18.0.1]:5701 [jet] [0.6-SNAPSHOT] Execution of job 52f2-7c29-757c-ecbb, execution 1d40-0a57-86ec-cced failed in 350 ms
java.lang.RuntimeException: Unknown type.  Value = 0x73726576
	at deepboof.io.torch7.TorchType.valueToType(TorchType.java:54)
	at deepboof.io.torch7.ParseBinaryTorch7.readType(ParseBinaryTorch7.java:59)
	at deepboof.io.torch7.ParseTorch7.parseNext(ParseTorch7.java:79)
	at deepboof.io.torch7.ParseTorch7.parse(ParseTorch7.java:68)
	at deepboof.io.torch7.ParseTorch7.parseOne(ParseTorch7.java:44)
	at deepboof.io.torch7.ParseTorch7.parseIntoBoof(ParseTorch7.java:51)
	at boofcv.deepboof.ImageClassifierVggCifar10.loadModel(ImageClassifierVggCifar10.java:77)
	at ClassifierProcessor.init(ClassifierProcessor.java:48)
	at com.hazelcast.jet.core.AbstractProcessor.init(AbstractProcessor.java:98)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.init(ProcessorTasklet.java:129)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.submitCooperativeTasklets(TaskletExecutionService.java:136)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.beginExecute(TaskletExecutionService.java:95)
	at com.hazelcast.jet.impl.execution.ExecutionContext.beginExecution(ExecutionContext.java:124)
	at com.hazelcast.jet.impl.operation.StartExecutionOperation.doRun(StartExecutionOperation.java:49)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:45)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:569)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:554)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:513)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60)
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:628)
	at com.hazelcast.jet.impl.MasterContext.invoke(MasterContext.java:589)
	at com.hazelcast.jet.impl.MasterContext.invokeStartExecution(MasterContext.java:401)
	at com.hazelcast.jet.impl.MasterContext.onInitStepCompleted(MasterContext.java:319)
	at com.hazelcast.jet.impl.MasterContext.lambda$invoke$19(MasterContext.java:606)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:134)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)
	at com.hazelcast.jet.impl.MasterContext.invoke(MasterContext.java:592)
	at com.hazelcast.jet.impl.MasterContext.tryStartJob(MasterContext.java:211)
	at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:267)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitOrJoinJob$1(JobCoordinationService.java:191)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
	at com.hazelcast.jet.impl.MasterContext.lambda$invoke$19(MasterContext.java:597)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:134)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipants$21(MasterContext.java:625)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
[hz._hzInstance_1_jet.async.thread-2] ERROR com.hazelcast.jet.impl.operation.CancelExecutionOperation - [172.18.0.1]:5701 [jet] [0.6-SNAPSHOT] job 52f2-7c29-757c-ecbb, execution 1d40-0a57-86ec-cced not found for coordinator [172.18.0.1]:5701 for 'CancelExecutionOperation'
com.hazelcast.jet.core.TopologyChangedException: job 52f2-7c29-757c-ecbb, execution 1d40-0a57-86ec-cced not found for coordinator [172.18.0.1]:5701 for 'CancelExecutionOperation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:263)
	at com.hazelcast.jet.impl.operation.CancelExecutionOperation.run(CancelExecutionOperation.java:58)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:569)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:554)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:513)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60)
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:628)
	at com.hazelcast.jet.impl.MasterContext.invoke(MasterContext.java:589)
	at com.hazelcast.jet.impl.MasterContext.lambda$cancelExecute$8(MasterContext.java:411)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
[WARNING] 
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unknown type.  Value = 0x73726576
    at java.util.concurrent.CompletableFuture.reportGet (CompletableFuture.java:357)
    at java.util.concurrent.CompletableFuture.get (CompletableFuture.java:1895)
    at com.hazelcast.jet.Job.lambda$join$0 (Job.java:95)
    at com.hazelcast.jet.impl.util.Util.uncheckRun (Util.java:98)
    at com.hazelcast.jet.Job.join (Job.java:95)
    at RealtimeImageRecognition.main (RealtimeImageRecognition.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.RuntimeException: Unknown type.  Value = 0x73726576
    at deepboof.io.torch7.TorchType.valueToType (TorchType.java:54)
    at deepboof.io.torch7.ParseBinaryTorch7.readType (ParseBinaryTorch7.java:59)
    at deepboof.io.torch7.ParseTorch7.parseNext (ParseTorch7.java:79)
    at deepboof.io.torch7.ParseTorch7.parse (ParseTorch7.java:68)
    at deepboof.io.torch7.ParseTorch7.parseOne (ParseTorch7.java:44)
    at deepboof.io.torch7.ParseTorch7.parseIntoBoof (ParseTorch7.java:51)
    at boofcv.deepboof.ImageClassifierVggCifar10.loadModel (ImageClassifierVggCifar10.java:77)
    at ClassifierProcessor.init (ClassifierProcessor.java:48)
    at com.hazelcast.jet.core.AbstractProcessor.init (AbstractProcessor.java:98)
    at com.hazelcast.jet.impl.execution.ProcessorTasklet.init (ProcessorTasklet.java:129)
    at com.hazelcast.jet.impl.execution.TaskletExecutionService.submitCooperativeTasklets (TaskletExecutionService.java:136)
    at com.hazelcast.jet.impl.execution.TaskletExecutionService.beginExecute (TaskletExecutionService.java:95)
    at com.hazelcast.jet.impl.execution.ExecutionContext.beginExecution (ExecutionContext.java:124)
    at com.hazelcast.jet.impl.operation.StartExecutionOperation.doRun (StartExecutionOperation.java:49)
    at com.hazelcast.jet.impl.operation.AsyncOperation.run (AsyncOperation.java:45)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run (OperationRunnerImpl.java:194)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run (OperationExecutorImpl.java:406)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute (OperationExecutorImpl.java:433)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal (Invocation.java:569)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke (Invocation.java:554)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0 (Invocation.java:513)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke (Invocation.java:207)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke (InvocationBuilderImpl.java:60)
    at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants (MasterContext.java:628)
    at com.hazelcast.jet.impl.MasterContext.invoke (MasterContext.java:589)
    at com.hazelcast.jet.impl.MasterContext.invokeStartExecution (MasterContext.java:401)
    at com.hazelcast.jet.impl.MasterContext.onInitStepCompleted (MasterContext.java:319)
    at com.hazelcast.jet.impl.MasterContext.lambda$invoke$19 (MasterContext.java:606)
    at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0 (ExceptionUtil.java:134)
    at java.util.concurrent.CompletableFuture.uniWhenComplete (CompletableFuture.java:760)
    at java.util.concurrent.CompletableFuture.uniWhenCompleteStage (CompletableFuture.java:778)
    at java.util.concurrent.CompletableFuture.whenComplete (CompletableFuture.java:2140)
    at com.hazelcast.jet.impl.MasterContext.invoke (MasterContext.java:592)
    at com.hazelcast.jet.impl.MasterContext.tryStartJob (MasterContext.java:211)
    at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob (JobCoordinationService.java:267)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitOrJoinJob$1 (JobCoordinationService.java:191)
    at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run (CachedExecutorServiceDelegate.java:227)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun (HazelcastManagedThread.java:64)
    at com.hazelcast.util.executor.HazelcastManagedThread.run (HazelcastManagedThread.java:80)
    at ------ submitted from ------. (Unknown Source)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve (InvocationFuture.java:127)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException (InvocationFuture.java:79)
    at com.hazelcast.spi.impl.AbstractInvocationFuture.get (AbstractInvocationFuture.java:147)
    at com.hazelcast.jet.impl.MasterContext.lambda$invoke$19 (MasterContext.java:597)
    at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0 (ExceptionUtil.java:134)
    at java.util.concurrent.CompletableFuture.uniWhenComplete (CompletableFuture.java:760)
    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire (CompletableFuture.java:736)
    at java.util.concurrent.CompletableFuture.postComplete (CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.complete (CompletableFuture.java:1962)
    at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipants$21 (MasterContext.java:625)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun (HazelcastManagedThread.java:64)
    at com.hazelcast.util.executor.HazelcastManagedThread.run (HazelcastManagedThread.java:80)
    at ------ submitted from ------. (Unknown Source)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve (InvocationFuture.java:127)
    at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run (AbstractInvocationFuture.java:243)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun (HazelcastManagedThread.java:64)
    at com.hazelcast.util.executor.HazelcastManagedThread.run (HazelcastManagedThread.java:80)
    at ------ submitted from ------. (Unknown Source)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve (InvocationFuture.java:127)
    at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run (AbstractInvocationFuture.java:243)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun (HazelcastManagedThread.java:64)
    at com.hazelcast.util.executor.HazelcastManagedThread.run (HazelcastManagedThread.java:80)

```

**Comment by eminn** [comment]
I am closing this one since the problems with this demo has been solved the fixes has been verified on multiple machines.

Please clone the repository with git-lfs installed and initialized.

If the issue continues to appear on your machine please re-open this.

**Comment by dbrimley** [comment]
My issue with this is that the error message does not indicate the cause of failure which is the missing GIT LFS.

Can you make sure we have an appropriate error message and that the system fails fast if it is unable to find GIT LFS

**Comment by dbrimley** [comment]
There's also no mention of git lfs in the README.md only in the super README.md

**Comment by m-david** [comment]
I know it's been a while since closed but I just cloned the latest repo and tried to run on my mac with this same issue.  I also ran this on fresh install of Ubuntu 18.04.

I've already executed:
>git lfs install
>git lfs ls-files

**Comment by m-david** [comment]
Just to be clear, it runs with exact error on Ubuntu 18.04

**Comment by wildnez** [comment]
Same problem encountered on latest code:

com.hazelcast.jet.core.TopologyChangedException: job 5355-5531-6e29-fed6, execution d7ca-98fd-d260-7c81 not found for coordinator [192.168.43.198]:5704 for 'TerminateExecutionOperation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:294)
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:59)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:648)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:633)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:592)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61)
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:233)
	at com.hazelcast.jet.impl.MasterJobContext.lambda$cancelExecutionInvocations$9(MasterJobContext.java:575)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
[hz._hzInstance_1_jet.async.thread-6] ERROR com.hazelcast.jet.impl.MasterJobContext - [192.168.43.198]:5704 [jet] [3.0] Execution of job '5355-5531-6e29-fed6', execution d7ca-98fd-d260-7c81 failed after 209 ms
java.lang.RuntimeException: Unknown type.  Value = 0x73726576
	at deepboof.io.torch7.TorchType.valueToType(TorchType.java:54)
	at deepboof.io.torch7.ParseBinaryTorch7.readType(ParseBinaryTorch7.java:59)
	at deepboof.io.torch7.ParseTorch7.parseNext(ParseTorch7.java:79)
	at deepboof.io.torch7.ParseTorch7.parse(ParseTorch7.java:68)
	at deepboof.io.torch7.ParseTorch7.parseOne(ParseTorch7.java:44)
	at deepboof.io.torch7.ParseTorch7.parseIntoBoof(ParseTorch7.java:51)
	at boofcv.deepboof.ImageClassifierVggCifar10.loadModel(ImageClassifierVggCifar10.java:77)
	at RealTimeImageRecognition.lambda$classifierContext$5c1f2912$1(RealTimeImageRecognition.java:197)
	at com.hazelcast.jet.function.FunctionEx.apply(FunctionEx.java:41)
	at com.hazelcast.jet.impl.processor.TransformUsingContextP.init(TransformUsingContextP.java:77)
	at com.hazelcast.jet.core.AbstractProcessor.init(AbstractProcessor.java:81)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.init(ProcessorTasklet.java:221)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.submitCooperativeTasklets(TaskletExecutionService.java:166)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.beginExecute(TaskletExecutionService.java:130)
	at com.hazelcast.jet.impl.execution.ExecutionContext.beginExecution(ExecutionContext.java:136)
	at com.hazelcast.jet.impl.JobExecutionService.beginExecution(JobExecutionService.java:328)
	at com.hazelcast.jet.impl.operation.StartExecutionOperation.doRun(StartExecutionOperation.java:44)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:50)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:648)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:633)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:592)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61)
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:233)
	at com.hazelcast.jet.impl.MasterJobContext.invokeStartExecution(MasterJobContext.java:445)
	at com.hazelcast.jet.impl.MasterJobContext.onInitStepCompleted(MasterJobContext.java:422)
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipants$0(MasterContext.java:242)
	at com.hazelcast.jet.impl.util.Util$2.onResponse(Util.java:172)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:256)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

**Comment by eminn** [comment]
@m-david, @dbrimley, @wildnez 

I think I've found the issue, git lfs stores the files as pointers and you need to issue checkout/pull command on git lfs to convert those pointers with the actual files.

So the commands to get the file is should be like the following and those needs to be run inside the repository directory;

```
git lfs install
git lfs pull
```

After that it successfully runs the demo. I've checked this on Mac OS and Ubuntu.

I'll update the READMEs regarding that.

**Comment by mtishchuk** [comment]
> I am closing this one since the problems with this demo has been solved the fixes has been verified on multiple machines.

Got same exception while testing gracefull shutfown one node in cluster. Is it possible to see the PR that fixs this error for this demo? I just have no idea what is this and how to fix it.
