### ISSUE TITLE
OOME on RealtimeImageRecognition 

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast-jet-demos#24]
```
3a, execution 4d00-9fdb-c59a-0ae2 initialized
[hz._hzInstance_1_jet.cached.thread-2] INFO com.hazelcast.jet.impl.operation.StartExecutionOperation - [192.168.43.157]:5701 [jet] [0.6-SNAPSHOT] Start execution of job 448b-ec68-4d6a-ad3a, execution 4d00-9fdb-c59a-0ae2 from coordinator [192.168.43.157]:5701
[hz._hzInstance_1_jet.cached.thread-2] ERROR com.hazelcast.jet.impl.MasterContext - [192.168.43.157]:5701 [jet] [0.6-SNAPSHOT] Exception during callback
java.lang.OutOfMemoryError: Java heap space
at deepboof.io.torch7.ParseBinaryTorch7.readArrayFloat(ParseBinaryTorch7.java:148)
at deepboof.io.torch7.ParseTorch7.parseStorage(ParseTorch7.java:243)
at deepboof.io.torch7.ParseTorch7.parseTorchObject(ParseTorch7.java:150)
at deepboof.io.torch7.ParseTorch7.parseNext(ParseTorch7.java:89)
at deepboof.io.torch7.ParseTorch7.parseTensor(ParseTorch7.java:217)
at deepboof.io.torch7.ParseTorch7.parseTorchObject(ParseTorch7.java:152)
at deepboof.io.torch7.ParseTorch7.parseNext(ParseTorch7.java:89)
at deepboof.io.torch7.ParseTorch7.parseTable(ParseTorch7.java:304)
at deepboof.io.torch7.ParseTorch7.parseNext(ParseTorch7.java:99)
at deepboof.io.torch7.ParseTorch7.parseTorchObject(ParseTorch7.java:163)
at deepboof.io.torch7.ParseTorch7.parseNext(ParseTorch7.java:89)
at deepboof.io.torch7.ParseTorch7.parseTable(ParseTorch7.java:304)
at deepboof.io.torch7.ParseTorch7.parseNext(ParseTorch7.java:99)
at deepboof.io.torch7.ParseTorch7.parseTable(ParseTorch7.java:304)
at deepboof.io.torch7.ParseTorch7.parseNext(ParseTorch7.java:99)
at deepboof.io.torch7.ParseTorch7.parseTorchObject(ParseTorch7.java:163)
at deepboof.io.torch7.ParseTorch7.parseNext(ParseTorch7.java:89)
at deepboof.io.torch7.ParseTorch7.parseTable(ParseTorch7.java:304)
at deepboof.io.torch7.ParseTorch7.parseNext(ParseTorch7.java:99)
at deepboof.io.torch7.ParseTorch7.parseTable(ParseTorch7.java:304)
at deepboof.io.torch7.ParseTorch7.parseNext(ParseTorch7.java:99)
at deepboof.io.torch7.ParseTorch7.parseTorchObject(ParseTorch7.java:163)
at deepboof.io.torch7.ParseTorch7.parseNext(ParseTorch7.java:89)
at deepboof.io.torch7.ParseTorch7.parse(ParseTorch7.java:68)
at deepboof.io.torch7.ParseTorch7.parseOne(ParseTorch7.java:44)
at deepboof.io.torch7.ParseTorch7.parseIntoBoof(ParseTorch7.java:51)
at boofcv.deepboof.ImageClassifierVggCifar10.loadModel(ImageClassifierVggCifar10.java:77)
at ClassifierProcessor.init(ClassifierProcessor.java:48)
at com.hazelcast.jet.core.AbstractProcessor.init(AbstractProcessor.java:98)
at com.hazelcast.jet.impl.execution.ProcessorTasklet.init(ProcessorTasklet.java:129)
at com.hazelcast.jet.impl.execution.TaskletExecutionService.submitCooperativeTasklets(TaskletExecutionService.java:136)
at com.hazelcast.jet.impl.execution.TaskletExecutionService.beginExecute(TaskletExecutionService.java:95)
at ------ submitted from ------.(Unknown Source)
at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
at com.hazelcast.jet.impl.MasterContext.lambda$invoke$19(MasterContext.java:597)
at com.hazelcast.jet.impl.MasterContext$$Lambda$205/911616689.accept(Unknown Source)
at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:134)
at com.hazelcast.jet.impl.util.ExceptionUtil$$Lambda$82/1051794848.accept(Unknown Source)
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2132)
at com.hazelcast.jet.impl.MasterContext.invoke(MasterContext.java:592)
at com.hazelcast.jet.impl.MasterContext.invokeStartExecution(MasterContext.java:401)
at com.hazelcast.jet.impl.MasterContext.onInitStepCompleted(MasterContext.java:319)
at com.hazelcast.jet.impl.MasterContext$$Lambda$147/1527681111.accept(Unknown Source)
at com.hazelcast.jet.impl.MasterContext.lambda$invoke$19(MasterContext.java:606)
at com.hazelcast.jet.impl.MasterContext$$Lambda$205/911616689.accept(Unknown Source)
at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:134)
at com.hazelcast.jet.impl.util.ExceptionUtil$$Lambda$82/1051794848.accept(Unknown Source)
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2132)
at com.hazelcast.jet.impl.MasterContext.invoke(MasterContext.java:592)
at com.hazelcast.jet.impl.MasterContext.tryStartJob(MasterContext.java:211)
at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:267)
at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitOrJoinJob$1(JobCoordinationService.java:191)
at com.hazelcast.jet.impl.JobCoordinationService$$Lambda$74/1332738458.run(Unknown Source)
at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
[hz._hzInstance_1_jet.async.thread-5] ERROR com.hazelcast.jet.impl.execution.TaskletExecutionService - [192.168.43.157]:5701 [jet] [0.6-SNAPSHOT] Exception during callback
java.lang.NullPointerException
at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.lambda$new$1(TaskletExecutionService.java:337)
at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker$$Lambda$214/132172009.accept(Unknown Source)
at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:134)
at com.hazelcast.jet.impl.util.ExceptionUtil$$Lambda$82/1051794848.accept(Unknown Source)
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2257)
at com.hazelcast.jet.impl.execution.ExecutionContext.cancelExecution(ExecutionContext.java:156)
at com.hazelcast.jet.impl.operation.CancelExecutionOperation.run(CancelExecutionOperation.java:59)
at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:569)
at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:554)
at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:513)
at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60)
at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:628)
at com.hazelcast.jet.impl.MasterContext.invoke(MasterContext.java:589)
at com.hazelcast.jet.impl.MasterContext.lambda$cancelExecute$8(MasterContext.java:411)
at com.hazelcast.jet.impl.MasterContext$$Lambda$223/1043673787.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

```

**Comment by eminn** [comment]
It was caused by configuration of JVM with `-Xmx512m` which was not enough.
