### ISSUE TITLE
customer churn : mvn clean install : kafka hangs on tests

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-jet-demos#43]
running ```mvn clean install``` runs the test suites.  Kafka hangs...

```
2018-02-08 07:40:05.076  WARN 8241 --- [.async.thread-3] com.hazelcast.jet.impl.MasterContext     : [172.18.0.1]:5701 [jet] [0.5] Execution of job fd5d-7242-a8ba-0fd5, execution 37b1-57d3-7158-6866 failed in 305331 ms

com.hazelcast.jet.JetException: Exception in ProcessorTasklet{vertex=streamKafka, processor=com.hazelcast.jet.impl.connector.kafka.StreamKafkaP@57aa242d}: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:173) ~[hazelcast-jet-0.5.jar:0.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
	at ------ submitted from ------.(Unknown Source) ~[na:na]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127) ~[hazelcast-jet-0.5.jar:0.5]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79) ~[hazelcast-jet-0.5.jar:0.5]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147) ~[hazelcast-jet-0.5.jar:0.5]
	at com.hazelcast.jet.impl.MasterContext.lambda$invoke$15(MasterContext.java:551) [hazelcast-jet-0.5.jar:0.5]
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:132) ~[hazelcast-jet-0.5.jar:0.5]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[na:1.8.0_161]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[na:1.8.0_161]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_161]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_161]
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipants$19(MasterContext.java:600) [hazelcast-jet-0.5.jar:0.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[hazelcast-jet-0.5.jar:0.5]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[hazelcast-jet-0.5.jar:0.5]
Caused by: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata

```

**Comment by rimogitz** [comment]
PLease note this project is refactored and added back to demos as JetChurnPredictor . Executing this module only requires running the command > spring-boot:run.  results of batch scoring of contracts for churn is logged in log file.
